name: tp1
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  flutter_svg: ^1.0.0
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/players/
    - assets/images/teams/
    - assets/images/logo.png
    - assets/api/nba2024stats.json
    - assets/api/nbaTeams.json